# GNS3 Connection Settings
gns3:
  server_url: "http://localhost:3080"
  project_name: "IRS_RL_Testbed"

# Node IPs
node_ips:
  kali: "192.168.206.10"
  win10: "192.168.177.10"
  router: "192.168.206.1"

# SSH Credentials
credentials:
  kali:
    user: "kali"
    pass: "kali"
  win10:
    user: "rashan"
    pass: "win@123"
  router:
    user: "root"
    pass: "gns3"

# Dataset path
dataset_path: "data/UNSW_NB15_testing-set.csv"

# Model paths
model_path: "models/random_forest_model.pkl"
dqn_model_path: "models/dqn_model.h5"

# RL parameters
learning_rate: 0.001
gamma: 0.95
epsilon_start: 1.0
epsilon_min: 0.01
epsilon_decay: 0.995
memory_size: 10000
batch_size: 64